### ISSUE TITLE
Tutorial Step 3 doesn't work

### ISSUE THREAD

**Issue by deraeler** [JeremyLikness/azure-fn-file-process-hol#1]
In Azure Storage Explorer, when attempting to create the Blob Container "import" by following your instructions, the Explorer just spins forever with a "Loading..." message under "Blob Containers". 
I got the Emulator in init sing my existing SQL instance, though those instructions were anything but clear.  As far as authenticating to the Emulator, I have no idea how to sort through all of these options. I can't tell if that's where the Explorer is getting hung up.The behavior is the same whether I try the creation under Emulator (Default Ports) (key), or local-1 (Key) - which was created when I Attempted to specify an auth method in the dialog presented and selecting local emulator and taking the defaults.
I'm unable to get any value out of this tutorial after installing all this software and spending hours trying to understand this.
Appreciate the help.

![azure_storage_explorer_blob_creation_fail](https://user-images.githubusercontent.com/53059131/74132294-46aa8c00-4bb4-11ea-9c3f-c144927115ce.JPG)

**Comment by deraeler** [comment]
The prior Step didn't include the instruction to issue the emulator "Start" command (only "init").
I got the import container in Explorer to appear once I did this and the emulator started, however i'm seeing errors in the subsequent step (See attachment).

I repeated the data folder upload (See attachment), yet the function just site there listening on the port, no idea what happened as a result of the errors in RED.

![data_upload_in_emulator](https://user-images.githubusercontent.com/53059131/74203674-71412700-4c3e-11ea-804a-c32ec694f089.JPG)


![azure_function_blob_connection_fail](https://user-images.githubusercontent.com/53059131/74203523-f2e48500-4c3d-11ea-8ab0-08373b76d029.JPG)

**Comment by JeremyLikness** [comment]
The latest emulator is not backwards compatible with earlier versions. You may need to update the SDK version in the project. I will take a look at it when I am able and check in a fix if I am able.

**Comment by deraeler** [comment]
Try to put yourself in my shoes for a moment.


I'm a legacy assembler/C/C+++/PHP developer.

I've committed to a Microsoft Developer Certification training program for
Azure.

In order to attend/complete these classes, I need to be "experienced in
developing applications for .NET".

My VERY FIST attempt at programming with .NET results in a tutorial
experience that blows up all over me.
I mean, it couldn't be worse.

I have no support form Microsoft.

I have nothing but forum resources to figure out why the instructions I've
filled PRECISELY simply explode everywhere.

I know what it's like to be a busy developer.  But you put this out there,
and if you can't support it, frankly it shouldn't be there.

I don't have the time to decompose every stupid resource I attempt to use
to LEARN.

Honestly, I'm ready to put a gun to my head with this stuff.
Microsoft....what was I thinking?

**Comment by JeremyLikness** [comment]
I recommend checking out [Microsoft Learn](https://docs.microsoft.com/learn?WT.mc_id=learn-github-jeliknes) ... there you will find tons of tutorials/hands-on labs with a built-in sandbox that are up-to-date and maintained. If I'm unable to fix this lab, I will remove it.

**Comment by JeremyLikness** [comment]
Archiving the repo until I can build a more up to date example
